fixtures:
  repositories:
    powershell:     git://github.com/joshcooper/puppetlabs-powershell.git
    windows_common: git://github.com/openstack-hyper-v/puppet-windows_common.git
  symlinks:
    hyper_v: "#{source_dir}"
